---
- include_vars: secrets.yml
- name: install fish and starship
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - fish
    - starship
- name: Change default shell to fish
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_bin }}"
  become: yes
- name: Ensure Config directory exists
  file:
    path: "{{ fish_conf }}"
    state: directory
- name: Template in main config
  template:
    src: "{{ role_path }}/templates/config.fish"
    dest: "{{ fish_conf }}/config.fish"
    backup: yes
    force: yes
- name: copy additional configuration
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ fish_conf }}"
    backup: yes
  loop:
    - fish_plugins
    - conf.d
- name: copy in starship config
  copy:
    src: "{{ role_path }}/files/starship.toml"
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    backup: yes
    force: yes
- name: Install fisher if not present
  block:
    - name: Ensure functions dir exists
      file:
        path: "{{ fish_conf }}/functions"
        state: directory
    - name: fetch fisher function file fff
      get_url:
        url: https://git.io/fisher
        dest: "{{ fish_conf }}/functions/fisher.fish"
    - name: Install/Update fisher packages
      shell:
        cmd: "fisher update"
        executable: "{{ fish_bin }}"
