- name: Check for pyenv
  stat:
    path: "{{ pyenv_path }}"
  register: result
- name: Install pyenv and pyenv-virtualenv
  when: result.stat.exists == false
  block:
    - name: Install pyenv
      git:
        repo: https://github.com/pyenv/pyenv
        dest: "{{ pyenv_path }}"
    - name: Install pyenv-virtualenv plugin
      git:
        repo: https://github.com/pyenv/pyenv-virtualenv
        dest: "{{ pyenv_path }}/plugins/pyenv-virtualenv"

