---
- name: install neovim
  package:
    name: neovim
    state: latest
- name: install vim-plug
  block:
    - file:
        path: "{{ nvim_autoload_dir }}"
        state: directory
    - get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ nvim_autoload_dir }}"
- name: template in config
  template:
    src: "{{ role_path }}/templates/init.vim"
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    force: no
- name: run PlugInstall
  shell: nvim --headless +PlugInstall +qa
