---
- name: install neovim
  community.general.homebrew:
    name: neovim
    state: head
- name: install vim-plug
  block:
    - file:
        path: "{{ nvim_autoload_dir }}"
        state: directory
    - get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ nvim_autoload_dir }}"
- name: template in config
  block:
    - name: ensure directories exist
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
      loop:
        - .config/nvim
        - .config/nvim/plugin
    - name: copy in init.vim 
      copy:
        src: "init.vim"
        dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
        backup: yes
    - name: template core options
      template:
        src: "{{ role_path }}/templates/core_options.vim"
        dest: "{{ ansible_env.HOME }}/.config/nvim/plugin/core_options.vim"
        backup: yes
    - name: copy in plugin files 
      copy:
        src: "plugin"
        dest: "{{ ansible_env.HOME }}/.config/nvim/"
        backup: yes
- name: run PlugInstall and PlugUpdate
  shell: nvim --headless +PlugInstall +PlugUpdate +qa
