---
- name: install cli tools
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - asdf
    - exa
    - ripgrep
    - the_silver_searcher
    - fzy
    - jq
    - entr
    - boxes
    - ranger
    - fzf
    - fd
    - gnupg
    - pinentry-mac

- name: add gpg-agent config
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.gnupg/{{ item }}"
    backup: yes
  loop:
    - gpg-agent.conf
    - gpg.conf

