---
- name: install cli tools
  package:
    name: "{{ packages }}"
    state: latest

- name: add gpg-agent config
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.gnupg/{{ item }}"
    backup: yes
  loop:
    - gpg-agent.conf
    - gpg.conf

